"""create core domain tables

Revision ID: 4cd6c8553ab4
Revises:
Create Date: 2026-08-07 20:55:40.948685

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4cd6c8553ab4"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "config",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_config")),
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
    )
    op.create_table(
        "memories",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("type", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_memories_project_id_projects"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memories")),
        sa.UniqueConstraint("project_id", "id", name="uq_memories_project_id_id"),
    )
    op.create_table(
        "observations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("processed_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'processed', 'discarded')",
            name=op.f("ck_observations_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_observations_project_id_projects"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_observations")),
    )
    op.create_table(
        "memory_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("memory_id", sa.String(length=36), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("context", sa.Text(), nullable=True),
        sa.Column("metadata", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "sequence >= 1",
            name=op.f("ck_memory_versions_sequence_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["memory_id"],
            ["memories.id"],
            name=op.f("fk_memory_versions_memory_id_memories"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memory_versions")),
        sa.UniqueConstraint("memory_id", "sequence", name="uq_memory_versions_memory_id_sequence"),
    )
    op.create_table(
        "relationships",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("from_memory_id", sa.String(length=36), nullable=False),
        sa.Column("to_memory_id", sa.String(length=36), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "from_memory_id <> to_memory_id",
            name=op.f("ck_relationships_not_self"),
        ),
        sa.ForeignKeyConstraint(
            ["from_memory_id"],
            ["memories.id"],
            name=op.f("fk_relationships_from_memory_id_memories"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_relationships_project_id_projects"),
        ),
        sa.ForeignKeyConstraint(
            ["to_memory_id"],
            ["memories.id"],
            name=op.f("fk_relationships_to_memory_id_memories"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_relationships")),
    )
    op.create_table(
        "confidence_history",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("memory_version_id", sa.String(length=36), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("recorded_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "score >= 0.0 AND score <= 1.0",
            name=op.f("ck_confidence_history_score_range"),
        ),
        sa.ForeignKeyConstraint(
            ["memory_version_id"],
            ["memory_versions.id"],
            name=op.f("fk_confidence_history_memory_version_id_memory_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_confidence_history")),
    )
    op.create_table(
        "evidence",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("memory_version_id", sa.String(length=36), nullable=False),
        sa.Column("evidence_type", sa.Text(), nullable=False),
        sa.Column("ref", sa.Text(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["memory_version_id"],
            ["memory_versions.id"],
            name=op.f("fk_evidence_memory_version_id_memory_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("evidence")
    op.drop_table("confidence_history")
    op.drop_table("relationships")
    op.drop_table("memory_versions")
    op.drop_table("observations")
    op.drop_table("memories")
    op.drop_table("projects")
    op.drop_table("config")
    # ### end Alembic commands ###
