"""add snapshot tables

Revision ID: 69e731c92c89
Revises: 67efef70fb0c
Create Date: 2026-08-09 00:32:09.442670

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "69e731c92c89"
down_revision: str | Sequence[str] | None = "67efef70fb0c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "snapshots",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("parent_id", sa.String(length=36), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["snapshots.id"], name=op.f("fk_snapshots_parent_id_snapshots")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_snapshots_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_snapshots")),
    )
    op.create_table(
        "snapshot_members",
        sa.Column("snapshot_id", sa.String(length=36), nullable=False),
        sa.Column("memory_version_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["memory_version_id"],
            ["memory_versions.id"],
            name=op.f("fk_snapshot_members_memory_version_id_memory_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["snapshots.id"],
            name=op.f("fk_snapshot_members_snapshot_id_snapshots"),
        ),
        sa.PrimaryKeyConstraint(
            "snapshot_id", "memory_version_id", name=op.f("pk_snapshot_members")
        ),
    )
    op.create_table(
        "snapshot_relationships",
        sa.Column("snapshot_id", sa.String(length=36), nullable=False),
        sa.Column("relationship_id", sa.String(length=36), nullable=False),
        sa.Column("from_memory_id", sa.String(length=36), nullable=False),
        sa.Column("to_memory_id", sa.String(length=36), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["relationship_id"],
            ["relationships.id"],
            name=op.f("fk_snapshot_relationships_relationship_id_relationships"),
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["snapshots.id"],
            name=op.f("fk_snapshot_relationships_snapshot_id_snapshots"),
        ),
        sa.PrimaryKeyConstraint(
            "snapshot_id", "relationship_id", name=op.f("pk_snapshot_relationships")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("snapshot_relationships")
    op.drop_table("snapshot_members")
    op.drop_table("snapshots")
    # ### end Alembic commands ###
