"""add branch tables

Revision ID: f8e261e677cb
Revises: 69e731c92c89
Create Date: 2026-08-10 01:18:26.107262

"""

from collections.abc import Sequence
from uuid import uuid4

import sqlalchemy as sa
from alembic import op

from chronicle.utils.time import utcnow

# revision identifiers, used by Alembic.
revision: str = "f8e261e677cb"
down_revision: str | Sequence[str] | None = "69e731c92c89"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

DEFAULT_BRANCH_NAME = "main"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "branches",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_branches_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_branches")),
        sa.UniqueConstraint("project_id", "name", name="uq_branches_project_id_name"),
    )
    op.create_table(
        "branch_members",
        sa.Column("branch_id", sa.String(length=36), nullable=False),
        sa.Column("memory_id", sa.String(length=36), nullable=False),
        sa.Column("memory_version_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["branch_id"], ["branches.id"], name=op.f("fk_branch_members_branch_id_branches")
        ),
        sa.ForeignKeyConstraint(
            ["memory_id"], ["memories.id"], name=op.f("fk_branch_members_memory_id_memories")
        ),
        sa.ForeignKeyConstraint(
            ["memory_version_id"],
            ["memory_versions.id"],
            name=op.f("fk_branch_members_memory_version_id_memory_versions"),
        ),
        sa.PrimaryKeyConstraint("branch_id", "memory_id", name=op.f("pk_branch_members")),
    )
    with op.batch_alter_table("projects") as batch_op:
        batch_op.add_column(
            sa.Column(
                "default_branch_id",
                sa.String(length=36),
                sa.ForeignKey("branches.id", name=op.f("fk_projects_default_branch_id_branches")),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "current_branch_id",
                sa.String(length=36),
                sa.ForeignKey("branches.id", name=op.f("fk_projects_current_branch_id_branches")),
                nullable=True,
            )
        )
    with op.batch_alter_table("snapshots") as batch_op:
        batch_op.add_column(
            sa.Column(
                "branch_id",
                sa.String(length=36),
                sa.ForeignKey("branches.id", name=op.f("fk_snapshots_branch_id_branches")),
                nullable=True,
            )
        )
    # ### end Alembic commands ###

    connection = op.get_bind()
    created_at = utcnow()
    project_ids = connection.execute(sa.text("SELECT id FROM projects")).scalars().all()
    for project_id in project_ids:
        branch_id = str(uuid4())
        connection.execute(
            sa.text(
                "INSERT INTO branches (id, project_id, name, is_default, created_at) "
                "VALUES (:id, :project_id, :name, 1, :created_at)"
            ),
            {"id": branch_id, "project_id": project_id, "name": DEFAULT_BRANCH_NAME, "created_at": created_at},
        )
        connection.execute(
            sa.text(
                "UPDATE projects SET default_branch_id = :branch_id, current_branch_id = :branch_id "
                "WHERE id = :project_id"
            ),
            {"branch_id": branch_id, "project_id": project_id},
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("snapshots") as batch_op:
        batch_op.drop_column("branch_id")
    with op.batch_alter_table("projects") as batch_op:
        batch_op.drop_column("current_branch_id")
        batch_op.drop_column("default_branch_id")
    op.drop_table("branch_members")
    op.drop_table("branches")
    # ### end Alembic commands ###